@echo off
echo Starting compile...
start D:\Tools\apache-maven-3.3.3\bin\mvn compile
echo Starting run...
start D:\Tools\apache-maven-3.3.3\bin\mvn exec:java -Dexec.mainClass="com.husou.search.controller.MainAPIController"